services:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:${DB_PORT}"
    env_file:
      - .env
    networks:
      - medistock-red-global

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
        - ./:/var/www
    depends_on:
      - postgres
    networks:
      - medistock-red-global

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
        - "8000:8000"
    volumes:
        - ./:/var/www
        - ./Docker/nginx/:/etc/nginx/conf.d/
    networks:
        - medistock-red-global

  mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
        - '1025:1025'
        - '8025:8025'
      networks:
        - medistock-red-global

networks:
  medistock-red-global:
    external: true
